In [1]:
import pandas as pd

In [2]:
frame = pd.read_csv('new_conditional_metrics.csv')

In [3]:
frame.head()

              base target     flow  dim  flow_l1  target_l1  diff_l1
0  ConditionalAR_2   AR_1      MAF   10    0.998      1.005    1.448
1  ConditionalAR_2   AR_1      MAF   15    1.001      0.991    0.673
2  ConditionalAR_2   AR_1      MAF   20    0.983      0.959    0.620
3  ConditionalAR_2   AR_1  RealNVP   10    1.004      1.001    1.086
4  ConditionalAR_2   AR_1  RealNVP   15    0.989      1.037    1.274

In [4]:
frame

                base target     flow  dim  flow_l1  target_l1  diff_l1
0    ConditionalAR_2   AR_1      MAF   10    0.998      1.005    1.448
1    ConditionalAR_2   AR_1      MAF   15    1.001      0.991    0.673
2    ConditionalAR_2   AR_1      MAF   20    0.983      0.959    0.620
3    ConditionalAR_2   AR_1  RealNVP   10    1.004      1.001    1.086
4    ConditionalAR_2   AR_1  RealNVP   15    0.989      1.037    1.274
..               ...    ...      ...  ...      ...        ...      ...
187  ConditionalMA_1   MA_2      MAF   15    1.012      0.956    1.173
188  ConditionalMA_1   MA_2      MAF   20    1.028      1.040    1.148
189  ConditionalMA_1   MA_2  RealNVP   10    1.002      1.001    0.426
190  ConditionalMA_1   MA_2  RealNVP   15    1.002      0.923    1.008
191  ConditionalMA_1   MA_2  RealNVP   20    0.993      0.968    1.071

[192 rows x 7 columns]

In [5]:
worst_rows = frame.groupby(['target'])['diff_l1'].idxmax()
best_rows = frame.groupby(['target'])['diff_l1'].idxmin()

In [6]:
frame.iloc[worst_rows]

                base target     flow  dim  flow_l1  target_l1  diff_l1
74              MA_2   AR_1      MAF   20    1.158      0.909    1.965
10   ConditionalAR_2   AR_2  RealNVP   15    1.005      2.502    3.359
14   ConditionalAR_2   MA_1      MAF   20    0.983      1.058    1.448
164  ConditionalAR_1   MA_2      MAF   20    0.999      0.958    1.527

In [7]:
frame.iloc[best_rows]

                base target     flow  dim  flow_l1  target_l1  diff_l1
120             MA_1   AR_1      MAF   10    1.006      1.007    0.120
174  ConditionalMA_1   AR_2      MAF   10    0.999      1.000    0.493
60              AR_2   MA_1      MAF   10    0.998      0.998    0.110
69              AR_2   MA_2  RealNVP   10    1.000      1.000    0.130

In [8]:
import numpy as np
conditional_bases = frame[frame['base'].str.contains('Conditional')]
conditional_bases.index = np.arange(96)

In [9]:
conditional_bases

               base target     flow  dim  flow_l1  target_l1  diff_l1
0   ConditionalAR_2   AR_1      MAF   10    0.998      1.005    1.448
1   ConditionalAR_2   AR_1      MAF   15    1.001      0.991    0.673
2   ConditionalAR_2   AR_1      MAF   20    0.983      0.959    0.620
3   ConditionalAR_2   AR_1  RealNVP   10    1.004      1.001    1.086
4   ConditionalAR_2   AR_1  RealNVP   15    0.989      1.037    1.274
..              ...    ...      ...  ...      ...        ...      ...
91  ConditionalMA_1   MA_2      MAF   15    1.012      0.956    1.173
92  ConditionalMA_1   MA_2      MAF   20    1.028      1.040    1.148
93  ConditionalMA_1   MA_2  RealNVP   10    1.002      1.001    0.426
94  ConditionalMA_1   MA_2  RealNVP   15    1.002      0.923    1.008
95  ConditionalMA_1   MA_2  RealNVP   20    0.993      0.968    1.071

[96 rows x 7 columns]

In [10]:
best_conditional_rows = conditional_bases.groupby(['target'])['diff_l1'].idxmin()
max(best_conditional_rows)

87

In [11]:
conditional_bases.iloc[best_conditional_rows]

               base target     flow  dim  flow_l1  target_l1  diff_l1
50  ConditionalAR_1   AR_1      MAF   20    0.996      1.004    0.444
78  ConditionalMA_1   AR_2      MAF   10    0.999      1.000    0.493
87  ConditionalMA_1   MA_1  RealNVP   10    1.002      1.002    0.132
42  ConditionalMA_2   MA_2      MAF   10    0.998      0.999    0.213