In [1]:
import pandas as pd

In [2]:
frame = pd.read_csv('new_metrics.csv')

In [3]:
frame.head()

  base target     flow  dim  flow_l1  target_l1  diff_l1
0  iid   AR_1      MAF    2      1.0        1.0    0.526
1  iid   AR_1      MAF    3      1.0        1.0    0.294
2  iid   AR_1  RealNVP    2      1.0        1.0    0.124
3  iid   AR_1  RealNVP    3      1.0        1.0    0.638
4  iid   AR_2      MAF    3      1.0        1.0    0.744

In [4]:
frame

    base target     flow  dim  flow_l1  target_l1  diff_l1
0    iid   AR_1      MAF    2      1.0        1.0    0.526
1    iid   AR_1      MAF    3      1.0        1.0    0.294
2    iid   AR_1  RealNVP    2      1.0        1.0    0.124
3    iid   AR_1  RealNVP    3      1.0        1.0    0.638
4    iid   AR_2      MAF    3      1.0        1.0    0.744
5    iid   AR_2  RealNVP    3      1.0        1.0    0.676
6    iid   MA_1      MAF    2      1.0        1.0    0.035
7    iid   MA_1      MAF    3      1.0        1.0    0.084
8    iid   MA_1  RealNVP    2      1.0        1.0    0.030
9    iid   MA_1  RealNVP    3      1.0        1.0    0.057
10   iid   MA_2      MAF    3      1.0        1.0    0.132
11   iid   MA_2  RealNVP    3      1.0        1.0    0.070
12  AR_1   AR_1      MAF    2      1.0        1.0    0.231
13  AR_1   AR_1      MAF    3      1.0        1.0    0.306
14  AR_1   AR_1  RealNVP    2      1.0        1.0    0.329
15  AR_1   AR_1  RealNVP    3      1.0        1.0    0.203
16  AR_1   AR_2      MAF    3      1.0        1.0    0.484
17  AR_1   AR_2  RealNVP    3      1.0        1.0    1.101
18  AR_1   MA_1      MAF    2      1.0        1.0    0.066
19  AR_1   MA_1      MAF    3      1.0        1.0    0.058
20  AR_1   MA_1  RealNVP    2      1.0        1.0    0.109
21  AR_1   MA_1  RealNVP    3      1.0        1.0    0.049
22  AR_1   MA_2      MAF    3      1.0        1.0    0.181
23  AR_1   MA_2  RealNVP    3      1.0        1.0    0.054
24  AR_2   AR_1      MAF    3      1.0        1.0    0.770
25  AR_2   AR_1  RealNVP    3      1.0        1.0    0.383
26  AR_2   AR_2      MAF    3      1.0        1.0    0.444
27  AR_2   AR_2  RealNVP    3      1.0        1.0    0.923
28  AR_2   MA_1      MAF    3      1.0        1.0    0.037
29  AR_2   MA_1  RealNVP    3      1.0        1.0    0.163
30  AR_2   MA_2      MAF    3      1.0        1.0    0.322
31  AR_2   MA_2  RealNVP    3      1.0        1.0    0.038
32  MA_1   AR_1      MAF    2      1.0        1.0    0.427
33  MA_1   AR_1      MAF    3      1.0        1.0    0.827
34  MA_1   AR_1  RealNVP    2      1.0        1.0    0.379
35  MA_1   AR_1  RealNVP    3      1.0        1.0    0.111
36  MA_1   AR_2      MAF    3      1.0        1.0    0.489
37  MA_1   AR_2  RealNVP    3      1.0        1.0    0.850
38  MA_1   MA_1      MAF    2      1.0        1.0    0.048
39  MA_1   MA_1      MAF    3      1.0        1.0    0.058
40  MA_1   MA_1  RealNVP    2      1.0        1.0    0.036
41  MA_1   MA_1  RealNVP    3      1.0        1.0    0.048
42  MA_1   MA_2      MAF    3      1.0        1.0    0.044
43  MA_1   MA_2  RealNVP    3      1.0        1.0    0.061
44  MA_2   AR_1      MAF    3      1.0        1.0    0.617
45  MA_2   AR_1  RealNVP    3      1.0        1.0    0.776
46  MA_2   AR_2      MAF    3      1.0        1.0    0.694
47  MA_2   AR_2  RealNVP    3      1.0        1.0    0.724
48  MA_2   MA_1      MAF    3      1.0        1.0    0.045
49  MA_2   MA_1  RealNVP    3      1.0        1.0    0.225
50  MA_2   MA_2      MAF    3      1.0        1.0    0.054
51  MA_2   MA_2  RealNVP    3      1.0        1.0    0.148

In [12]:
worst_rows = frame.groupby(['target'])['diff_l1'].idxmax()
best_rows = frame.groupby(['target'])['diff_l1'].idxmin()

In [13]:
frame.iloc[worst_rows]

    base target     flow  dim  flow_l1  target_l1  diff_l1
33  MA_1   AR_1      MAF    3      1.0        1.0    0.827
17  AR_1   AR_2  RealNVP    3      1.0        1.0    1.101
49  MA_2   MA_1  RealNVP    3      1.0        1.0    0.225
30  AR_2   MA_2      MAF    3      1.0        1.0    0.322

In [14]:
frame.iloc[best_rows]

    base target     flow  dim  flow_l1  target_l1  diff_l1
35  MA_1   AR_1  RealNVP    3      1.0        1.0    0.111
26  AR_2   AR_2      MAF    3      1.0        1.0    0.444
8    iid   MA_1  RealNVP    2      1.0        1.0    0.030
31  AR_2   MA_2  RealNVP    3      1.0        1.0    0.038